---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gok3s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gok3s
  template:
    metadata:
      labels:
        app: gok3s
    spec:
      containers:
      - name: gok3s-container
        image: clhoultby/k3s:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
